spring.application.name=resumemanagement



spring.datasource.url=jdbc:mysql://localhost:3306/resume_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Gourav

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true